name: cyberwatch

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

# to consider: the use of action jobs to breakout each task
# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

jobs:
  run-ransomwatch:
    runs-on: ubuntu-latest
    timeout-minutes: 170
    environment: CI
    steps:
      - name: Generate RSS Feed
        run: |
          DEEPL_API: ${{ secrets.DEEPL_API }}
          python3 rss.py
      - name: Save changes
        run: |  
          DATE=$(date -Iseconds)
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit --all --message "Updated by Crontab on $DATE" || echo "no changes to commit" 
          git push
