name: Update Cyberattacks Reports RSS Feed

on:
  push:
    branches:
        - main
    paths:
      - 'cyberattacks.json'
  workflow_dispatch:

permissions: write-all

env:
  LANG: "fr_FR.UTF-8"

jobs:
  run-flux_rss:
    runs-on: ubuntu-latest
    timeout-minutes: 170
    environment: CI
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: fr_FR.UTF-8
        run: |
          sudo locale-gen fr_FR.UTF-8
          sudo update-locale LANG=fr_FR.UTF-8
      - name: Install dependencies
        run: |
          pip3 install -r rss_requirements.txt
      - name: Generate RSS
        run: |
          python3 cyberattacks-feed.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./
          push_options: --force
      - name: Save changes
        run: |  
          DATE=$(date -Iseconds)
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull origin main
          git commit --all --message "Updated by Crontab on $DATE" || echo "no changes to commit" 
          git push origin main
